### ISSUE TITLE
Find HCF

### ISSUE THREAD

**Issue by lineage-merlin** [lineage-merlin/JAVA#1]
Given a positive number, your task is to calculate the HCF.
Input Format
Two numbers

Print HCF of two number.
Sample Input

3 45

Sample Output
3

**Comment by lineage-merlin** [comment]
Add in MATH folder

**Comment by XIZT07** [comment]
can i take up the issue?

**Comment by kchatr** [comment]
Can I be assigned this issue @lineage-merlin?

**Comment by megabyte98** [comment]
can you please assign this issue to me i would like to contribute?

**Comment by LiteBrick204** [comment]
can you please assign this issue to me @lineage-merlin ?

**Comment by aastha-b** [comment]
Can I work on this issue?
