### ISSUE TITLE
Print HelloWorld

### ISSUE THREAD

**Issue by Alleny244** [lineage-merlin/JAVA#28]
## Hello Forks !!
* All you have to do is to add Java Source code in the folder HelloWorld of this repositiory <br/> which  prints **Welcome to the world of open source :)** <br/>instead of printing the traditional  **hello world**  output

* Sample Output = **Welcome to the world of open source :)**

### Happy Open Sourcing....

**Comment by Ansh04122001** [comment]
can i work on this program

**Comment by Alleny244** [comment]
> can i work on this program

Yes you can

**Comment by Yash10299** [comment]
Where is the HelloWorld folder??

**Comment by Alleny244** [comment]
> Where is the HelloWorld folder??

Its in the java repository please refresh your browser

**Comment by Palritika1107** [comment]
Can I work on this too ,since it is still open?

**Comment by Alleny244** [comment]
> Can I work on this too ,since it is still open?

ok you can

**Comment by hamzzy** [comment]
done #32
