### ISSUE TITLE
Pascal's Triangle

### ISSUE THREAD

**Issue by lineage-merlin** [lineage-merlin/JAVA#6]
Given an integer N, print Pascal Triangle upto N rows.
Input Format

Single integer N.
Constraints

N <= 10
Output Format

Print pascal triangle.
Sample Input

5

Sample Output
```


    1
   1 1
  1 2 1
 1 3 3 1
1 4 6 4 1


```

**Comment by touchSarcasticSad** [comment]
Can i take this ?

**Comment by Pranav1642** [comment]
Hey, Can I work on this?
