### ISSUE TITLE
Calculate nPr

### ISSUE THREAD

**Issue by lineage-merlin** [lineage-merlin/JAVA#8]
You have to calculate the permutation.
Input format
Two numbers n and r.

Sample Input
7 3

Output
210

**Comment by lineage-merlin** [comment]
Add in MATH folder

**Comment by psyduck1203** [comment]
Hey I'll do this can you assign me this issue !!!!

**Comment by Yash10299** [comment]
in which language should it be done??

**Comment by psyduck1203** [comment]
@Yash10299 i'm working on this, maybe you can look upon another issue !!! Thankyou ;)
